### ISSUE TITLE
NumericRegex.IsMatch performance

### ISSUE THREAD

**Issue by depler** [manuelbl/QrCodeGenerator#5]
I see some points to improve performance, for example replacing `NumericRegex.IsMatch(text)` to `text.All(char.IsDigit)` and similar cases. Do you plan to implement that or this just a strict port from Java version?

**Comment by manuelbl** [comment]
You are welcome to provide a pull request. I'll happily accept it if it doesn't deviate too much from Nayuki's QR code generator (Java version) as I'd like to stay in sync with any relevant changes.

If you are looking for a major speed improvement, choose a fixed mask. That will likely cut the execution time by about factor 7!

**Comment by nayuki** [comment]
The regex test is not a significant area for speed optimization.

The significant speed-ups I identified and implemented can be seen in my [Fast QR Code generator library](https://www.nayuki.io/page/fast-qr-code-generator-library) write-up and [codebase](https://github.com/nayuki/Fast-QR-Code-generator). The most important improvements I recall are:

* Packing modules/pixels into the bits of 32-bit integers instead of using one `boolean` (1 byte) per module.
* Precomputing the multiplication tables for Reed-Solomon ECC encoding.
* Precomputing the fixed patterns and mask patterns.
* Precomputing the zigzag scan order.

**Comment by depler** [comment]
@nayuki and this fast QR library is only available for Java, right?

**Comment by nayuki** [comment]
Yes, my fast QR is implemented in Java only. Regarding performance, the [web page](https://www.nayuki.io/page/fast-qr-code-generator-library) discusses benchmark timings from my computer. Using the slow QR lib, even the worst-case largest barcode only takes 7 milliseconds to generate on my computer.
